# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for Mothbot desktop builds.

Usage:
  python -m PyInstaller --clean --noconfirm apps/packaging/pyinstaller/mothbot_desktop.spec
"""

from pathlib import Path
import importlib.util
import os
import sys

from PyInstaller.utils.hooks import collect_data_files, collect_submodules


def _resolve_project_dir():
    spec_dir = Path(SPECPATH).resolve()
    for candidate in (spec_dir, *spec_dir.parents):
        if (candidate / "pyproject.toml").exists():
            return candidate
    # Fallback to current layout if pyproject discovery fails.
    return spec_dir.parents[2]


project_dir = _resolve_project_dir()
ai_dir = project_dir.parent
release_version = os.environ.get("MOTHBOT_RELEASE_VERSION", "").strip().lstrip("v")
if not release_version:
    try:
        import tomllib
        release_version = tomllib.loads((project_dir / "pyproject.toml").read_text())["project"]["version"]
    except Exception:
        release_version = "0.1.0"

hiddenimports = []
for package in [
    "gradio",
    "gradio_client",
    "ultralytics",
    "onnxruntime",
    "fiftyone",
    "fiftyone_brain",
    "open_clip",
    "bioclip",
	"pystray",
    "pystray._win32",   # Windows backend
    "pystray._darwin",  # macOS backend
    "pystray._xorg",    # Linux backend
]:
    hiddenimports += collect_submodules(package)

datas = []
for package in [
    "gradio",
    "gradio_client",
    "groovy",
    "ultralytics",
    "onnxruntime",
    "fiftyone",
    "fiftyone_brain",
    "safehttpx",
    "open_clip",
    "bioclip",
]:
    datas += collect_data_files(package)


def _package_dir(package_name):
    spec = importlib.util.find_spec(package_name)
    if spec is None:
        return None
    if spec.submodule_search_locations:
        return Path(next(iter(spec.submodule_search_locations)))
    if spec.origin:
        return Path(spec.origin).parent
    return None


# Some Gradio internals read their own source files at runtime.
# Include full package trees so those files are available in frozen mode.
for package_name in ["gradio", "safehttpx", "groovy", "open_clip", "bioclip"]:
    pkg_dir = _package_dir(package_name)
    if pkg_dir and pkg_dir.exists():
        datas.append((str(pkg_dir), package_name))

# Optional local files/directories that may or may not exist in every checkout.
for src in [
    project_dir / "artifacts",
    project_dir / "Mothbox_Main_Metadata_Field_Sheet_Example - Form responses 1.csv",
    project_dir / "SpeciesList_CountryIndonesia_TaxaInsecta_doi.org10.15468dl.8p8wua.csv",
    ai_dir / "exiftool-13.32_64",
]:
    if src.exists():
        if src.is_dir():
            datas.append((str(src), src.name))
        else:
            datas.append((str(src), "."))

# Bundle favicon.png into assets/ so tray icon and browser tab can find it.
favicon_png = project_dir / "assets" / "favicon.png"
if favicon_png.exists():
    datas.append((str(favicon_png), "assets"))

# Bundle DINOv2 weights into assets/ subfolder
dino_weights = project_dir / "assets" / "dinov2_vits14_pretrain.pth"
if dino_weights.exists():
    datas.append((str(dino_weights), "assets"))

# Bundle favicon.ico for the Windows exe icon.
favicon_ico = project_dir / "assets" / "favicon.ico"
if favicon_ico.exists():
    datas.append((str(favicon_ico), "assets"))

# Bundle mothbot.icns for the macOS app icon (generated by build_desktop_macos.sh).
mothbot_icns = project_dir / "assets" / "mothbot.icns"
if mothbot_icns.exists():
    datas.append((str(mothbot_icns), "assets"))

# Bundle explicit build/release version marker when available.
build_version_file = os.environ.get("MOTHBOT_VERSION_FILE", "").strip()
if build_version_file:
    version_path = Path(build_version_file)
    if version_path.exists():
        datas.append((str(version_path), "."))


a = Analysis(
    [str(project_dir / "apps" / "desktop_main.py")],
    pathex=[str(project_dir)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
	
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Mothbot",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
	icon=str(project_dir / "assets" / "favicon.ico"), 
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="Mothbot",
)

if sys.platform == "darwin":
    app = BUNDLE(
        coll,
        name="Mothbot.app",
        icon=str(mothbot_icns) if mothbot_icns.exists() else None,
        bundle_identifier="org.mothbox.desktop",
        info_plist={
            "CFBundleName": "Mothbot",
            "CFBundleDisplayName": "Mothbot",
            "CFBundleShortVersionString": release_version,
            "CFBundleVersion": release_version,
            "NSHighResolutionCapable": True,
        },
    )
